-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE topics (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 title TEXT NOT NULL,
 description TEXT,
 tag TEXT NOT NULL,
 post_count INTEGER DEFAULT 0,
 view_count INTEGER DEFAULT 0,
 is_hot BOOLEAN DEFAULT false,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE topics ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_topics ON topics
 FOR SELECT
 USING (true);

-- 插入一些初始热门话题
INSERT INTO topics (title, description, tag, is_hot) VALUES
('新手入门指南', '讨论仿写工具的使用技巧和常见问题', '新手', true),
('爆款创作技巧', '分享如何写出吸引人的开头和情节', '技巧', true),
('平台投稿经验', '交流各大网文平台的投稿心得', '平台', true),
('版权合规讨论', '探讨如何避免抄袭风险，安全创作', '法律', false),
('AI模型对比', '不同AI模型的仿写效果对比分析', '技术', false);

