-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

CREATE POLICY anon_select_approved_shares ON author_shares FOR SELECT USING (status = 'approved'); CREATE POLICY users_insert_own_shares ON author_shares FOR INSERT WITH CHECK (true); CREATE POLICY admins_select_all_shares ON author_shares FOR SELECT USING (true); CREATE POLICY admins_update_shares ON author_shares FOR UPDATE USING (true);
