-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE search_history (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
 keyword TEXT NOT NULL,
 search_type TEXT DEFAULT 'all' CHECK (search_type IN ('all', 'share', 'work', 'qa')),
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_search_history_user ON search_history(user_id, created_at DESC);

ALTER TABLE search_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY users_select_own_search_history ON search_history
 FOR SELECT
 USING (user_id = auth.uid());

CREATE POLICY users_insert_search_history ON search_history
 FOR INSERT
 WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY users_delete_own_search_history ON search_history
 FOR DELETE
 USING (user_id = auth.uid());

