-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE qa_posts (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
 title TEXT NOT NULL,
 content TEXT NOT NULL,
 category TEXT NOT NULL,
 tags JSONB DEFAULT '[]'::jsonb,
 view_count INTEGER DEFAULT 0,
 answer_count INTEGER DEFAULT 0,
 best_answer_id UUID,
 status TEXT DEFAULT 'open',
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE qa_posts ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_qa_posts ON qa_posts
 FOR SELECT
 USING (true);

CREATE POLICY users_insert_qa_posts ON qa_posts
 FOR INSERT
 WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY users_update_own_qa_posts ON qa_posts
 FOR UPDATE
 USING (user_id = auth.uid());

