-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

CREATE TABLE comment_likes (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), comment_id UUID NOT NULL REFERENCES comments(id) ON DELETE CASCADE, user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), UNIQUE(comment_id, user_id)); ALTER TABLE comment_likes ENABLE ROW LEVEL SECURITY; CREATE POLICY anon_select_comment_likes ON comment_likes FOR SELECT USING (true); CREATE POLICY users_insert_comment_likes ON comment_likes FOR INSERT WITH CHECK (auth.uid() = user_id); CREATE POLICY users_delete_own_comment_likes ON comment_likes FOR DELETE USING (auth.uid() = user_id); CREATE INDEX idx_comment_likes_comment_id ON comment_likes(comment_id); CREATE INDEX idx_comment_likes_user_id ON comment_likes(user_id);
