-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


ALTER TABLE author_shares ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_author_shares ON author_shares
 FOR SELECT
 USING (true);

CREATE POLICY users_insert_author_shares ON author_shares
 FOR INSERT
 WITH CHECK (true);

CREATE POLICY users_update_own_author_shares ON author_shares
 FOR UPDATE
 USING (auth.uid() = user_id);

CREATE POLICY users_delete_own_author_shares ON author_shares
 FOR DELETE
 USING (auth.uid() = user_id);

