-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

ALTER TABLE author_shares ADD COLUMN status TEXT NOT NULL DEFAULT 'pending'; ALTER TABLE author_shares ADD COLUMN reviewed_at TIMESTAMPTZ; ALTER TABLE author_shares ADD COLUMN reviewer_id UUID;
