-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

CREATE TABLE activation_keys (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), key_code TEXT NOT NULL UNIQUE, is_used BOOLEAN NOT NULL DEFAULT false, used_by UUID REFERENCES auth.users(id), activated_at TIMESTAMPTZ, expires_at TIMESTAMPTZ NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
