-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

ALTER TABLE activation_keys ENABLE ROW LEVEL SECURITY; CREATE POLICY anon_select_activation_keys ON activation_keys FOR SELECT USING (true); CREATE POLICY anon_insert_activation_keys ON activation_keys FOR INSERT WITH CHECK (true);
