-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE works_showcase (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
 title TEXT NOT NULL,
 genre TEXT NOT NULL,
 description TEXT,
 content_preview TEXT,
 cover_image TEXT,
 like_count INTEGER DEFAULT 0,
 view_count INTEGER DEFAULT 0,
 status TEXT DEFAULT 'published',
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE works_showcase ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_works ON works_showcase
 FOR SELECT
 USING (true);

CREATE POLICY users_insert_works ON works_showcase
 FOR INSERT
 WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY users_update_own_works ON works_showcase
 FOR UPDATE
 USING (user_id = auth.uid());

CREATE POLICY users_delete_own_works ON works_showcase
 FOR DELETE
 USING (user_id = auth.uid());

