-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE author_shares (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 user_id UUID REFERENCES auth.users(id),
 nickname TEXT NOT NULL,
 avatar_url TEXT,
 platform TEXT NOT NULL,
 title TEXT NOT NULL,
 income TEXT,
 story TEXT NOT NULL,
 background TEXT,
 breakthrough TEXT,
 current_status TEXT,
 advice TEXT,
 tips TEXT,
 achievement TEXT,
 monthly_income JSONB,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

