-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE user_achievements (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
 achievement_type TEXT NOT NULL,
 level INTEGER DEFAULT 1,
 unlocked_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 UNIQUE(user_id, achievement_type)
);

CREATE INDEX idx_achievements_user ON user_achievements(user_id);

ALTER TABLE user_achievements ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_achievements ON user_achievements
 FOR SELECT
 USING (true);

