-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE work_likes (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 work_id UUID REFERENCES works_showcase(id) ON DELETE CASCADE,
 user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 UNIQUE(work_id, user_id)
);

ALTER TABLE work_likes ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_work_likes ON work_likes
 FOR SELECT
 USING (true);

CREATE POLICY users_insert_work_likes ON work_likes
 FOR INSERT
 WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY users_delete_own_work_likes ON work_likes
 FOR DELETE
 USING (user_id = auth.uid());

