-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

ALTER TABLE comments ADD COLUMN IF NOT EXISTS like_count INTEGER DEFAULT 0; CREATE OR REPLACE FUNCTION increment_comment_likes(comment_id UUID) RETURNS VOID AS $$ BEGIN UPDATE comments SET like_count = like_count + 1 WHERE id = comment_id; END; $$ LANGUAGE plpgsql SECURITY DEFINER; CREATE OR REPLACE FUNCTION decrement_comment_likes(comment_id UUID) RETURNS VOID AS $$ BEGIN UPDATE comments SET like_count = GREATEST(like_count - 1, 0) WHERE id = comment_id; END; $$ LANGUAGE plpgsql SECURITY DEFINER;
