-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

ALTER TABLE templates ENABLE ROW LEVEL SECURITY; CREATE POLICY anon_select_public_templates ON templates FOR SELECT USING (is_public = true); CREATE POLICY users_select_own_templates ON templates FOR SELECT USING (created_by = auth.uid() OR is_public = true); CREATE POLICY users_insert_templates ON templates FOR INSERT WITH CHECK (true); CREATE POLICY users_update_own_templates ON templates FOR UPDATE USING (created_by = auth.uid()); CREATE POLICY users_delete_own_templates ON templates FOR DELETE USING (created_by = auth.uid());
