-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

CREATE TABLE templates (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name TEXT NOT NULL, description TEXT, template_config JSONB NOT NULL, is_public BOOLEAN NOT NULL DEFAULT false, created_by UUID REFERENCES auth.users(id), usage_count INTEGER NOT NULL DEFAULT 0, score INTEGER NOT NULL DEFAULT 0, scenario TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
