-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

ALTER TABLE rewrite_records ENABLE ROW LEVEL SECURITY; CREATE POLICY users_select_own_records ON rewrite_records FOR SELECT USING (user_id = auth.uid()); CREATE POLICY users_insert_records ON rewrite_records FOR INSERT WITH CHECK (true);
