-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

CREATE TABLE author_share_likes (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), share_id UUID REFERENCES author_shares(id) ON DELETE CASCADE, user_id UUID, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()); CREATE UNIQUE INDEX unique_like_per_user ON author_share_likes(share_id, user_id);
