-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE collections (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 target_type TEXT NOT NULL CHECK (target_type IN ('share', 'work')),
 target_id UUID NOT NULL,
 user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 UNIQUE(target_type, target_id, user_id)
);

CREATE INDEX idx_collections_user ON collections(user_id);

ALTER TABLE collections ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_collections ON collections
 FOR SELECT
 USING (true);

CREATE POLICY users_insert_collections ON collections
 FOR INSERT
 WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY users_delete_own_collections ON collections
 FOR DELETE
 USING (user_id = auth.uid());

