-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

ALTER TABLE author_share_likes ENABLE ROW LEVEL SECURITY; CREATE POLICY anon_select_share_likes ON author_share_likes FOR SELECT USING (true); CREATE POLICY anon_insert_share_likes ON author_share_likes FOR INSERT WITH CHECK (true); CREATE POLICY users_delete_own_likes ON author_share_likes FOR DELETE USING (user_id = auth.uid() OR user_id IS NULL);
