-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE follows (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 follower_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
 following_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
 UNIQUE(follower_id, following_id),
 CHECK (follower_id != following_id)
);

CREATE INDEX idx_follows_follower ON follows(follower_id);
CREATE INDEX idx_follows_following ON follows(following_id);

ALTER TABLE follows ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_follows ON follows
 FOR SELECT
 USING (true);

CREATE POLICY users_insert_follows ON follows
 FOR INSERT
 WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY users_delete_own_follows ON follows
 FOR DELETE
 USING (follower_id = auth.uid());

