-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

CREATE TABLE public.profiles (id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE, username TEXT UNIQUE NOT NULL, avatar_url TEXT, created_at TIMESTAMP DEFAULT NOW()); ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY; CREATE POLICY users_select_own_profile ON public.profiles FOR SELECT USING (auth.uid() = id); CREATE POLICY users_insert_own_profile ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id); CREATE POLICY users_update_own_profile ON public.profiles FOR UPDATE USING (auth.uid() = id) WITH CHECK (auth.uid() = id);
