-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE comments (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 target_type TEXT NOT NULL CHECK (target_type IN ('share', 'work', 'qa')),
 target_id UUID NOT NULL,
 user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
 content TEXT NOT NULL,
 parent_id UUID REFERENCES comments(id) ON DELETE CASCADE,
 like_count INTEGER DEFAULT 0,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_comments_target ON comments(target_type, target_id);
CREATE INDEX idx_comments_parent ON comments(parent_id);

ALTER TABLE comments ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_comments ON comments
 FOR SELECT
 USING (true);

CREATE POLICY users_insert_comments ON comments
 FOR INSERT
 WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY users_update_own_comments ON comments
 FOR UPDATE
 USING (user_id = auth.uid());

CREATE POLICY users_delete_own_comments ON comments
 FOR DELETE
 USING (user_id = auth.uid());

