-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE qa_answers (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 post_id UUID REFERENCES qa_posts(id) ON DELETE CASCADE,
 user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
 content TEXT NOT NULL,
 is_best_answer BOOLEAN DEFAULT false,
 like_count INTEGER DEFAULT 0,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE qa_posts
 ADD CONSTRAINT fk_best_answer
 FOREIGN KEY (best_answer_id) REFERENCES qa_answers(id) ON DELETE SET NULL;

ALTER TABLE qa_answers ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_select_qa_answers ON qa_answers
 FOR SELECT
 USING (true);

CREATE POLICY users_insert_qa_answers ON qa_answers
 FOR INSERT
 WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY users_update_own_qa_answers ON qa_answers
 FOR UPDATE
 USING (user_id = auth.uid());

