-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY; CREATE POLICY anon_select_messages ON public.messages FOR SELECT USING (true); CREATE POLICY anon_insert_messages ON public.messages FOR INSERT WITH CHECK (true);
