-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE email_verifications (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 email TEXT NOT NULL,
 verification_code TEXT NOT NULL,
 expires_at TIMESTAMPTZ NOT NULL,
 used BOOLEAN DEFAULT false,
 created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX idx_email_verifications_email ON email_verifications(email);
CREATE INDEX idx_email_verifications_expires ON email_verifications(expires_at);

ALTER TABLE email_verifications ENABLE ROW LEVEL SECURITY;

CREATE POLICY anon_insert_email_verifications ON email_verifications
 FOR INSERT
 WITH CHECK (true);

CREATE POLICY anon_select_email_verifications ON email_verifications
 FOR SELECT
 USING (true);

