-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================


CREATE TABLE reports (
 id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 target_type TEXT NOT NULL CHECK (target_type IN ('share', 'work', 'qa', 'comment')),
 target_id UUID NOT NULL,
 reporter_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
 reason TEXT NOT NULL,
 status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'reviewing', 'resolved', 'rejected')),
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_reports_target ON reports(target_type, target_id);

ALTER TABLE reports ENABLE ROW LEVEL SECURITY;

CREATE POLICY users_insert_reports ON reports
 FOR INSERT
 WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY anon_select_reports ON reports
 FOR SELECT
 USING (true);

