-- ============================================
-- 此文件由 Meoo Cloud 自动生成，请勿修改
-- This file is auto-generated by Meoo Cloud, DO NOT MODIFY
-- ============================================

CREATE TABLE rewrite_records (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), user_id UUID REFERENCES auth.users(id), original_text_length INTEGER NOT NULL, rewritten_text_length INTEGER NOT NULL, model_used TEXT NOT NULL, params_used JSONB, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
