// ============================================
// 此文件由 Meoo Cloud 自动生成，请勿修改
// This file is auto-generated by Meoo Cloud, DO NOT MODIFY
// ============================================

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      activation_keys: {
        Row: {
          activated_at: string | null
          created_at: string
          expires_at: string
          id: string
          is_used: boolean
          key_code: string
          used_by: string | null
        }
        Insert: {
          activated_at?: string | null
          created_at?: string
          expires_at: string
          id?: string
          is_used?: boolean
          key_code: string
          used_by?: string | null
        }
        Update: {
          activated_at?: string | null
          created_at?: string
          expires_at?: string
          id?: string
          is_used?: boolean
          key_code?: string
          used_by?: string | null
        }
        Relationships: []
      }
      author_share_likes: {
        Row: {
          created_at: string
          id: string
          share_id: string | null
          user_id: string | null
        }
        Insert: {
          created_at?: string
          id?: string
          share_id?: string | null
          user_id?: string | null
        }
        Update: {
          created_at?: string
          id?: string
          share_id?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "author_share_likes_share_id_fkey"
            columns: ["share_id"]
            referencedRelation: "author_shares"
            referencedColumns: ["id"]
          },
        ]
      }
      author_shares: {
        Row: {
          achievement: string | null
          advice: string | null
          avatar_url: string | null
          background: string | null
          breakthrough: string | null
          created_at: string
          current_status: string | null
          id: string
          images: Json | null
          income: string | null
          monthly_income: Json | null
          nickname: string
          platform: string
          published_at: string
          reviewed_at: string | null
          reviewer_id: string | null
          status: string
          story: string
          tips: string | null
          title: string
          user_id: string | null
        }
        Insert: {
          achievement?: string | null
          advice?: string | null
          avatar_url?: string | null
          background?: string | null
          breakthrough?: string | null
          created_at?: string
          current_status?: string | null
          id?: string
          images?: Json | null
          income?: string | null
          monthly_income?: Json | null
          nickname: string
          platform: string
          published_at?: string
          reviewed_at?: string | null
          reviewer_id?: string | null
          status?: string
          story: string
          tips?: string | null
          title: string
          user_id?: string | null
        }
        Update: {
          achievement?: string | null
          advice?: string | null
          avatar_url?: string | null
          background?: string | null
          breakthrough?: string | null
          created_at?: string
          current_status?: string | null
          id?: string
          images?: Json | null
          income?: string | null
          monthly_income?: Json | null
          nickname?: string
          platform?: string
          published_at?: string
          reviewed_at?: string | null
          reviewer_id?: string | null
          status?: string
          story?: string
          tips?: string | null
          title?: string
          user_id?: string | null
        }
        Relationships: []
      }
      collections: {
        Row: {
          created_at: string
          id: string
          target_id: string
          target_type: string
          user_id: string | null
        }
        Insert: {
          created_at?: string
          id?: string
          target_id: string
          target_type: string
          user_id?: string | null
        }
        Update: {
          created_at?: string
          id?: string
          target_id?: string
          target_type?: string
          user_id?: string | null
        }
        Relationships: []
      }
      comment_likes: {
        Row: {
          comment_id: string
          created_at: string
          id: string
          user_id: string
        }
        Insert: {
          comment_id: string
          created_at?: string
          id?: string
          user_id: string
        }
        Update: {
          comment_id?: string
          created_at?: string
          id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "comment_likes_comment_id_fkey"
            columns: ["comment_id"]
            referencedRelation: "comments"
            referencedColumns: ["id"]
          },
        ]
      }
      comments: {
        Row: {
          content: string
          created_at: string
          id: string
          like_count: number | null
          parent_id: string | null
          target_id: string
          target_type: string
          user_id: string | null
        }
        Insert: {
          content: string
          created_at?: string
          id?: string
          like_count?: number | null
          parent_id?: string | null
          target_id: string
          target_type: string
          user_id?: string | null
        }
        Update: {
          content?: string
          created_at?: string
          id?: string
          like_count?: number | null
          parent_id?: string | null
          target_id?: string
          target_type?: string
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "comments_parent_id_fkey"
            columns: ["parent_id"]
            referencedRelation: "comments"
            referencedColumns: ["id"]
          },
        ]
      }
      email_verifications: {
        Row: {
          created_at: string | null
          email: string
          expires_at: string
          id: string
          used: boolean | null
          verification_code: string
        }
        Insert: {
          created_at?: string | null
          email: string
          expires_at: string
          id?: string
          used?: boolean | null
          verification_code: string
        }
        Update: {
          created_at?: string | null
          email?: string
          expires_at?: string
          id?: string
          used?: boolean | null
          verification_code?: string
        }
        Relationships: []
      }
      follows: {
        Row: {
          created_at: string
          follower_id: string | null
          following_id: string | null
          id: string
        }
        Insert: {
          created_at?: string
          follower_id?: string | null
          following_id?: string | null
          id?: string
        }
        Update: {
          created_at?: string
          follower_id?: string | null
          following_id?: string | null
          id?: string
        }
        Relationships: []
      }
      messages: {
        Row: {
          content: string
          created_at: string | null
          id: string
          is_read: boolean
          title: string
          type: string
        }
        Insert: {
          content: string
          created_at?: string | null
          id?: string
          is_read?: boolean
          title: string
          type?: string
        }
        Update: {
          content?: string
          created_at?: string | null
          id?: string
          is_read?: boolean
          title?: string
          type?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          avatar_url: string | null
          created_at: string | null
          id: string
          username: string
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string | null
          id: string
          username: string
        }
        Update: {
          avatar_url?: string | null
          created_at?: string | null
          id?: string
          username?: string
        }
        Relationships: []
      }
      qa_answers: {
        Row: {
          content: string
          created_at: string
          id: string
          is_best_answer: boolean | null
          like_count: number | null
          post_id: string | null
          user_id: string | null
        }
        Insert: {
          content: string
          created_at?: string
          id?: string
          is_best_answer?: boolean | null
          like_count?: number | null
          post_id?: string | null
          user_id?: string | null
        }
        Update: {
          content?: string
          created_at?: string
          id?: string
          is_best_answer?: boolean | null
          like_count?: number | null
          post_id?: string | null
          user_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "qa_answers_post_id_fkey"
            columns: ["post_id"]
            referencedRelation: "qa_posts"
            referencedColumns: ["id"]
          },
        ]
      }
      qa_posts: {
        Row: {
          answer_count: number | null
          best_answer_id: string | null
          category: string
          content: string
          created_at: string
          id: string
          status: string | null
          tags: Json | null
          title: string
          user_id: string | null
          view_count: number | null
        }
        Insert: {
          answer_count?: number | null
          best_answer_id?: string | null
          category: string
          content: string
          created_at?: string
          id?: string
          status?: string | null
          tags?: Json | null
          title: string
          user_id?: string | null
          view_count?: number | null
        }
        Update: {
          answer_count?: number | null
          best_answer_id?: string | null
          category?: string
          content?: string
          created_at?: string
          id?: string
          status?: string | null
          tags?: Json | null
          title?: string
          user_id?: string | null
          view_count?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "fk_best_answer"
            columns: ["best_answer_id"]
            referencedRelation: "qa_answers"
            referencedColumns: ["id"]
          },
        ]
      }
      reports: {
        Row: {
          created_at: string
          id: string
          reason: string
          reporter_id: string | null
          status: string | null
          target_id: string
          target_type: string
        }
        Insert: {
          created_at?: string
          id?: string
          reason: string
          reporter_id?: string | null
          status?: string | null
          target_id: string
          target_type: string
        }
        Update: {
          created_at?: string
          id?: string
          reason?: string
          reporter_id?: string | null
          status?: string | null
          target_id?: string
          target_type?: string
        }
        Relationships: []
      }
      rewrite_records: {
        Row: {
          created_at: string
          id: string
          model_used: string
          original_text_length: number
          params_used: Json | null
          rewritten_text_length: number
          user_id: string | null
        }
        Insert: {
          created_at?: string
          id?: string
          model_used: string
          original_text_length: number
          params_used?: Json | null
          rewritten_text_length: number
          user_id?: string | null
        }
        Update: {
          created_at?: string
          id?: string
          model_used?: string
          original_text_length?: number
          params_used?: Json | null
          rewritten_text_length?: number
          user_id?: string | null
        }
        Relationships: []
      }
      search_history: {
        Row: {
          created_at: string
          id: string
          keyword: string
          search_type: string | null
          user_id: string | null
        }
        Insert: {
          created_at?: string
          id?: string
          keyword: string
          search_type?: string | null
          user_id?: string | null
        }
        Update: {
          created_at?: string
          id?: string
          keyword?: string
          search_type?: string | null
          user_id?: string | null
        }
        Relationships: []
      }
      templates: {
        Row: {
          created_at: string
          created_by: string | null
          description: string | null
          id: string
          is_public: boolean
          name: string
          scenario: string | null
          score: number
          template_config: Json
          updated_at: string
          usage_count: number
        }
        Insert: {
          created_at?: string
          created_by?: string | null
          description?: string | null
          id?: string
          is_public?: boolean
          name: string
          scenario?: string | null
          score?: number
          template_config: Json
          updated_at?: string
          usage_count?: number
        }
        Update: {
          created_at?: string
          created_by?: string | null
          description?: string | null
          id?: string
          is_public?: boolean
          name?: string
          scenario?: string | null
          score?: number
          template_config?: Json
          updated_at?: string
          usage_count?: number
        }
        Relationships: []
      }
      topics: {
        Row: {
          created_at: string
          description: string | null
          id: string
          is_hot: boolean | null
          post_count: number | null
          tag: string
          title: string
          view_count: number | null
        }
        Insert: {
          created_at?: string
          description?: string | null
          id?: string
          is_hot?: boolean | null
          post_count?: number | null
          tag: string
          title: string
          view_count?: number | null
        }
        Update: {
          created_at?: string
          description?: string | null
          id?: string
          is_hot?: boolean | null
          post_count?: number | null
          tag?: string
          title?: string
          view_count?: number | null
        }
        Relationships: []
      }
      user_achievements: {
        Row: {
          achievement_type: string
          id: string
          level: number | null
          unlocked_at: string
          user_id: string | null
        }
        Insert: {
          achievement_type: string
          id?: string
          level?: number | null
          unlocked_at?: string
          user_id?: string | null
        }
        Update: {
          achievement_type?: string
          id?: string
          level?: number | null
          unlocked_at?: string
          user_id?: string | null
        }
        Relationships: []
      }
      work_likes: {
        Row: {
          created_at: string
          id: string
          user_id: string | null
          work_id: string | null
        }
        Insert: {
          created_at?: string
          id?: string
          user_id?: string | null
          work_id?: string | null
        }
        Update: {
          created_at?: string
          id?: string
          user_id?: string | null
          work_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "work_likes_work_id_fkey"
            columns: ["work_id"]
            referencedRelation: "works_showcase"
            referencedColumns: ["id"]
          },
        ]
      }
      works_showcase: {
        Row: {
          content_preview: string | null
          cover_image: string | null
          created_at: string
          description: string | null
          genre: string
          id: string
          like_count: number | null
          status: string | null
          title: string
          user_id: string | null
          view_count: number | null
        }
        Insert: {
          content_preview?: string | null
          cover_image?: string | null
          created_at?: string
          description?: string | null
          genre: string
          id?: string
          like_count?: number | null
          status?: string | null
          title: string
          user_id?: string | null
          view_count?: number | null
        }
        Update: {
          content_preview?: string | null
          cover_image?: string | null
          created_at?: string
          description?: string | null
          genre?: string
          id?: string
          like_count?: number | null
          status?: string | null
          title?: string
          user_id?: string | null
          view_count?: number | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      decrement_comment_likes: {
        Args: { comment_id: string }
        Returns: undefined
      }
      increment_comment_likes: {
        Args: { comment_id: string }
        Returns: undefined
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DefaultSchema = Database[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof Database },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof (Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        Database[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof Database }
  ? (Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      Database[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof Database },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof Database }
  ? Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof Database },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends { schema: keyof Database }
  ? Database[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof Database },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends { schema: keyof Database }
  ? Database[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof Database },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof Database
  }
    ? keyof Database[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends { schema: keyof Database }
  ? Database[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
