/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CoreRouteImport } from './routes/core'
import { Route as DeconstructRouteImport } from './routes/deconstruct'
import { Route as GlobalRankingsRouteImport } from './routes/global-rankings'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MoreRouteImport } from './routes/more'
import { Route as PlatformDetailRouteImport } from './routes/platform-detail'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as QaDetailRouteImport } from './routes/qa-detail'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TopicDetailRouteImport } from './routes/topic-detail'
import { Route as TutorialDetailRouteImport } from './routes/tutorial-detail'
import { Route as WorkflowRouteImport } from './routes/workflow'
import { Route as GuidePlatformsRouteImport } from './routes/guide.platforms'
import { Route as GuideSubmissionRouteImport } from './routes/guide.submission'
import { Route as GuideWritingTipsRouteImport } from './routes/guide.writing-tips'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreRoute = CoreRouteImport.update({
  id: '/core',
  path: '/core',
  getParentRoute: () => rootRouteImport,
} as any)
const DeconstructRoute = DeconstructRouteImport.update({
  id: '/deconstruct',
  path: '/deconstruct',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalRankingsRoute = GlobalRankingsRouteImport.update({
  id: '/global-rankings',
  path: '/global-rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformDetailRoute = PlatformDetailRouteImport.update({
  id: '/platform-detail',
  path: '/platform-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const QaDetailRoute = QaDetailRouteImport.update({
  id: '/qa-detail',
  path: '/qa-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicDetailRoute = TopicDetailRouteImport.update({
  id: '/topic-detail',
  path: '/topic-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialDetailRoute = TutorialDetailRouteImport.update({
  id: '/tutorial-detail',
  path: '/tutorial-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowRoute = WorkflowRouteImport.update({
  id: '/workflow',
  path: '/workflow',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidePlatformsRoute = GuidePlatformsRouteImport.update({
  id: '/guide/platforms',
  path: '/guide/platforms',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideSubmissionRoute = GuideSubmissionRouteImport.update({
  id: '/guide/submission',
  path: '/guide/submission',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideWritingTipsRoute = GuideWritingTipsRouteImport.update({
  id: '/guide/writing-tips',
  path: '/guide/writing-tips',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/community': typeof CommunityRoute
  '/core': typeof CoreRoute
  '/deconstruct': typeof DeconstructRoute
  '/global-rankings': typeof GlobalRankingsRoute
  '/messages': typeof MessagesRoute
  '/more': typeof MoreRoute
  '/platform-detail': typeof PlatformDetailRoute
  '/profile': typeof ProfileRoute
  '/qa-detail': typeof QaDetailRoute
  '/settings': typeof SettingsRoute
  '/topic-detail': typeof TopicDetailRoute
  '/tutorial-detail': typeof TutorialDetailRoute
  '/workflow': typeof WorkflowRoute
  '/guide/platforms': typeof GuidePlatformsRoute
  '/guide/submission': typeof GuideSubmissionRoute
  '/guide/writing-tips': typeof GuideWritingTipsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/community': typeof CommunityRoute
  '/core': typeof CoreRoute
  '/deconstruct': typeof DeconstructRoute
  '/global-rankings': typeof GlobalRankingsRoute
  '/messages': typeof MessagesRoute
  '/more': typeof MoreRoute
  '/platform-detail': typeof PlatformDetailRoute
  '/profile': typeof ProfileRoute
  '/qa-detail': typeof QaDetailRoute
  '/settings': typeof SettingsRoute
  '/topic-detail': typeof TopicDetailRoute
  '/tutorial-detail': typeof TutorialDetailRoute
  '/workflow': typeof WorkflowRoute
  '/guide/platforms': typeof GuidePlatformsRoute
  '/guide/submission': typeof GuideSubmissionRoute
  '/guide/writing-tips': typeof GuideWritingTipsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/community': typeof CommunityRoute
  '/core': typeof CoreRoute
  '/deconstruct': typeof DeconstructRoute
  '/global-rankings': typeof GlobalRankingsRoute
  '/messages': typeof MessagesRoute
  '/more': typeof MoreRoute
  '/platform-detail': typeof PlatformDetailRoute
  '/profile': typeof ProfileRoute
  '/qa-detail': typeof QaDetailRoute
  '/settings': typeof SettingsRoute
  '/topic-detail': typeof TopicDetailRoute
  '/tutorial-detail': typeof TutorialDetailRoute
  '/workflow': typeof WorkflowRoute
  '/guide/platforms': typeof GuidePlatformsRoute
  '/guide/submission': typeof GuideSubmissionRoute
  '/guide/writing-tips': typeof GuideWritingTipsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/community'
    | '/core'
    | '/deconstruct'
    | '/global-rankings'
    | '/messages'
    | '/more'
    | '/platform-detail'
    | '/profile'
    | '/qa-detail'
    | '/settings'
    | '/topic-detail'
    | '/tutorial-detail'
    | '/workflow'
    | '/guide/platforms'
    | '/guide/submission'
    | '/guide/writing-tips'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/community'
    | '/core'
    | '/deconstruct'
    | '/global-rankings'
    | '/messages'
    | '/more'
    | '/platform-detail'
    | '/profile'
    | '/qa-detail'
    | '/settings'
    | '/topic-detail'
    | '/tutorial-detail'
    | '/workflow'
    | '/guide/platforms'
    | '/guide/submission'
    | '/guide/writing-tips'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/community'
    | '/core'
    | '/deconstruct'
    | '/global-rankings'
    | '/messages'
    | '/more'
    | '/platform-detail'
    | '/profile'
    | '/qa-detail'
    | '/settings'
    | '/topic-detail'
    | '/tutorial-detail'
    | '/workflow'
    | '/guide/platforms'
    | '/guide/submission'
    | '/guide/writing-tips'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CommunityRoute: typeof CommunityRoute
  CoreRoute: typeof CoreRoute
  DeconstructRoute: typeof DeconstructRoute
  GlobalRankingsRoute: typeof GlobalRankingsRoute
  MessagesRoute: typeof MessagesRoute
  MoreRoute: typeof MoreRoute
  PlatformDetailRoute: typeof PlatformDetailRoute
  ProfileRoute: typeof ProfileRoute
  QaDetailRoute: typeof QaDetailRoute
  SettingsRoute: typeof SettingsRoute
  TopicDetailRoute: typeof TopicDetailRoute
  TutorialDetailRoute: typeof TutorialDetailRoute
  WorkflowRoute: typeof WorkflowRoute
  GuidePlatformsRoute: typeof GuidePlatformsRoute
  GuideSubmissionRoute: typeof GuideSubmissionRoute
  GuideWritingTipsRoute: typeof GuideWritingTipsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core': {
      id: '/core'
      path: '/core'
      fullPath: '/core'
      preLoaderRoute: typeof CoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deconstruct': {
      id: '/deconstruct'
      path: '/deconstruct'
      fullPath: '/deconstruct'
      preLoaderRoute: typeof DeconstructRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global-rankings': {
      id: '/global-rankings'
      path: '/global-rankings'
      fullPath: '/global-rankings'
      preLoaderRoute: typeof GlobalRankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform-detail': {
      id: '/platform-detail'
      path: '/platform-detail'
      fullPath: '/platform-detail'
      preLoaderRoute: typeof PlatformDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-detail': {
      id: '/qa-detail'
      path: '/qa-detail'
      fullPath: '/qa-detail'
      preLoaderRoute: typeof QaDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topic-detail': {
      id: '/topic-detail'
      path: '/topic-detail'
      fullPath: '/topic-detail'
      preLoaderRoute: typeof TopicDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorial-detail': {
      id: '/tutorial-detail'
      path: '/tutorial-detail'
      fullPath: '/tutorial-detail'
      preLoaderRoute: typeof TutorialDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflow': {
      id: '/workflow'
      path: '/workflow'
      fullPath: '/workflow'
      preLoaderRoute: typeof WorkflowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/platforms': {
      id: '/guide/platforms'
      path: '/guide/platforms'
      fullPath: '/guide/platforms'
      preLoaderRoute: typeof GuidePlatformsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/submission': {
      id: '/guide/submission'
      path: '/guide/submission'
      fullPath: '/guide/submission'
      preLoaderRoute: typeof GuideSubmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/writing-tips': {
      id: '/guide/writing-tips'
      path: '/guide/writing-tips'
      fullPath: '/guide/writing-tips'
      preLoaderRoute: typeof GuideWritingTipsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CommunityRoute: CommunityRoute,
  CoreRoute: CoreRoute,
  DeconstructRoute: DeconstructRoute,
  GlobalRankingsRoute: GlobalRankingsRoute,
  MessagesRoute: MessagesRoute,
  MoreRoute: MoreRoute,
  PlatformDetailRoute: PlatformDetailRoute,
  ProfileRoute: ProfileRoute,
  QaDetailRoute: QaDetailRoute,
  SettingsRoute: SettingsRoute,
  TopicDetailRoute: TopicDetailRoute,
  TutorialDetailRoute: TutorialDetailRoute,
  WorkflowRoute: WorkflowRoute,
  GuidePlatformsRoute: GuidePlatformsRoute,
  GuideSubmissionRoute: GuideSubmissionRoute,
  GuideWritingTipsRoute: GuideWritingTipsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
